"""Keystone canonical system model (Doc 05).

The single source of truth. Every front door (docs/voice/text/diagram) normalises
into this; every output (simulation/report/export) derives from it. Pure stdlib.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from keystone.provenance import Grounding  # evidence types (pure stdlib; no cycle)


class ComponentKind(str, Enum):
    CLIENT = "client"
    CDN = "cdn"
    LOAD_BALANCER = "load_balancer"
    API_GATEWAY = "api_gateway"
    APP_SERVER = "app_server"
    CACHE = "cache"
    SQL_DB = "sql_db"
    REPLICA = "replica"
    QUEUE = "queue"
    OBJECT_STORE = "object_store"
    EXTERNAL_API = "external_api"


# Component kinds that are a single point of failure when run as one instance.
_SPOF_KINDS = {
    ComponentKind.SQL_DB,
    ComponentKind.CACHE,
    ComponentKind.LOAD_BALANCER,
    ComponentKind.API_GATEWAY,
    ComponentKind.QUEUE,
}


@dataclass
class Component:
    id: str
    kind: ComponentKind
    name: str
    per_instance_rps: float           # service capacity per instance (req/s)
    instances: int = 1
    base_latency_ms: float = 1.0      # service time with no contention
    monthly_cost_per_instance: int = 0  # integer MINOR UNITS (USD cents/month) — harm floor: no float money (ADR-008)
    # Usage-based cost inputs (ADR-009 Tier 1). Declarative monthly volumes the engine multiplies by
    # the model's `PricingRates`. Default 0 → no usage cost, so existing models are byte-for-byte
    # unchanged. Non-negative ints (they drive money — harm floor). ASSUMPTION until grounded.
    egress_gb_per_month: int = 0      # GB egressed (internet / cross-region) per month
    storage_gb: int = 0               # GB stored (object/block/DB storage)
    requests_per_month: int = 0       # billable requests/month (API gateway, serverless, queue ops)
    # AI/LLM token volumes (ADR-009 Tier 2 part 2). For AI/agent components: tokens sent (input) and
    # generated (output) per month. Output is priced higher than input, so they are tracked separately.
    # Default 0 → no AI cost, so non-AI models are byte-for-byte unchanged. ASSUMPTION until grounded.
    llm_input_tokens_per_month: int = 0   # tokens sent to the model (prompt) per month
    llm_output_tokens_per_month: int = 0  # tokens generated by the model (completion) per month
    provenance: str = "assumption"    # component default: GROUNDED | GAP | ASSUMPTION
    # Per-metric grounding evidence (ADR-006/docs/12). A capacity becomes GROUNDED only when the
    # KB attaches a `Grounding` (value + band + citations) under that metric name; otherwise the
    # metric keeps the component `provenance` default. Empty = nothing grounded (the honest L0 state).
    # Set at construction (immutable evidence); the engine NEVER reads it (prime directive — grounding
    # changes the input number, never the math). `scaled()` shares components, which is correct: a
    # what-if keeps the same capacities, so the same groundings apply.
    groundings: dict[str, Grounding] = field(default_factory=dict)

    def __post_init__(self) -> None:
        # Harm floor (ADR-008): money is integer minor units (cents) — never a float (rounding
        # corrupts money). `bool` is an int subclass, so exclude it explicitly.
        c = self.monthly_cost_per_instance
        if isinstance(c, bool) or not isinstance(c, int):
            raise TypeError(
                f"monthly_cost_per_instance must be an int in minor units (cents), not {type(c).__name__} "
                f"({c!r}) — float money is forbidden by the harm floor")
        if c < 0:
            raise ValueError(f"monthly_cost_per_instance must be non-negative, got {c}")
        # `instances` multiplies cost (monthly_cost = monthly_cost_per_instance × instances), so a float
        # instances would make money a float — harm floor (ADR-008). It is a count of running units:
        # an int ≥ 1 (also blocks the 0-instance divide-by-zero in utilisation). `bool` excluded.
        n = self.instances
        if isinstance(n, bool) or not isinstance(n, int):
            raise TypeError(f"instances must be an int, not {type(n).__name__} ({n!r}) "
                            "— a float instance count would corrupt integer money (harm floor)")
        if n < 1:
            raise ValueError(f"instances must be >= 1, got {n}")
        # Usage volumes drive money, so hold them to the same harm-floor discipline: non-negative ints.
        for name in ("egress_gb_per_month", "storage_gb", "requests_per_month",
                     "llm_input_tokens_per_month", "llm_output_tokens_per_month"):
            v = getattr(self, name)
            if isinstance(v, bool) or not isinstance(v, int):
                raise TypeError(f"{name} must be a non-negative int, not {type(v).__name__} ({v!r})")
            if v < 0:
                raise ValueError(f"{name} must be non-negative, got {v}")

    def provenance_of(self, metric: str) -> str:
        """GROUNDED if this metric carries grounding evidence, else the component default."""
        g = self.groundings.get(metric)
        return g.provenance if g else self.provenance

    @property
    def capacity_rps(self) -> float:
        return self.per_instance_rps * self.instances

    @property
    def monthly_cost(self) -> float:
        return self.monthly_cost_per_instance * self.instances

    @property
    def is_spof(self) -> bool:
        return self.instances <= 1 and self.kind in _SPOF_KINDS


@dataclass
class FlowStep:
    component_id: str
    visit_prob: float = 1.0           # P(component is hit on this flow), e.g. cache-miss


@dataclass
class Flow:
    name: str
    share: float                      # fraction of total requests (Sum of shares == 1.0)
    path: list[FlowStep]


@dataclass
class Workload:
    system_rps: float
    description: str = ""


@dataclass
class Assumption:
    subject: str
    statement: str
    confidence: str = "med"           # low | med | high
    source: str = "assumption"        # llm_inferred | benchmark | user
    provenance: str = "ASSUMPTION"    # GROUNDED | GAP | ASSUMPTION


# Compute pricing models → integer **basis points** (per-10_000) of the on-demand list price that you
# still PAY (ADR-009 Tier 2 discount lever). Real deployments rarely pay list: a 1–3yr commitment or
# interruptible spot cuts the compute bill, so "full price" overstates a believable bill.
# Values were RESEARCHED + 3x adversarially verified (see `benchmarks/grounded_pricing_rates.json`,
# 2026-06-23) — central = % off RETAINED as bp; ratified by Bifola (#71 merged on "ratify #71").
# `on_demand` is 10_000 bp (100% — the default), so any model that does not opt into a discount is
# byte-for-byte unchanged. Integer bp keeps the discount math money-safe (round-half-up integer
# arithmetic — never a float; harm floor, ADR-008).
COMPUTE_PRICING_RETAINED_BP = {
    "on_demand":    10_000,   # list price, no commitment — the default
    "reserved_1yr":  7_000,   # ~30% off — 1yr no-upfront flexible (band 28–42% off); GROUNDED T2, 2/3 verified
    "reserved_3yr":  4_500,   # ~55% off — 3yr commitment (band 46–72% off); GROUNDED T1, 3/3 verified
    "spot":          2_300,   # ~77% off — interruptible spot/preemptible (band 55–91% off); GROUNDED T1, 2/3 verified
}


@dataclass
class PricingRates:
    """Per-unit cloud rates for usage-based cost (ADR-009 Tier 1) + the compute pricing model (Tier 2).
    Rates are integer **micro-USD** per unit (1 USD = 1_000_000 micro-USD; 1 cent = 10_000 micro-USD)
    so sub-cent rates are exact; the engine rounds the usage TOTAL to integer cents (harm floor, ADR-008
    — money is never a float). Defaults were RESEARCHED + 3x adversarially verified (devil's-advocate)
    against real vendor/aggregator pricing pages — see `benchmarks/grounded_pricing_rates.json` (2026-06-23)
    for the value, band, tier, and citations of each (ratified #71). `grounding.ground_pricing` attaches
    that evidence to `groundings` (keyed by rate id) so the report can show the rates as GROUNDED."""
    egress_micro_usd_per_gb: int = 90_000          # $0.09/GB internet egress, US first paid tier (band 0.087–0.12); GROUNDED T2, 3/3
    storage_micro_usd_per_gb_month: int = 21_000   # $0.021/GB-mo object storage standard (band 0.018–0.0253); GROUNDED T2, 3/3
    request_micro_usd_per_thousand: int = 3_000    # $3.00 per 1M API-gateway requests (band 1.00–3.50); GROUNDED T1, 3/3 (was a 3x-low guess)
    # AI/LLM per-token rates (ADR-009 Tier 2 part 2), micro-USD per 1_000 tokens. Output dearer than input.
    # Small/fast model class (GPT-4o-mini / Haiku / Gemini Flash) — real prices vary widely, see the band.
    llm_input_micro_usd_per_1k_tokens: int = 500    # $0.50 per 1M input tokens (band 0.10–1.00); GROUNDED T1, 3/3
    llm_output_micro_usd_per_1k_tokens: int = 4_000  # $4.00 per 1M output tokens (band 0.40–9.00); GROUNDED T1, 1/3 — band corrected by verifiers
    # Tier 2 discount lever: which compute pricing model the bill assumes. Default `on_demand` = list
    # price = no change to existing cost numbers. Applied to COMPUTE ONLY (per ADR-009 §2).
    compute_pricing: str = "on_demand"
    # Cited evidence per rate id (ADR-006 grounding, mirrors Component.groundings). Empty = not attached
    # (the honest default); `grounding.ground_pricing` fills it from grounded_pricing_rates.json when the
    # KB is active. The rate VALUES already equal the grounded centrals; this only carries the citations.
    groundings: dict[str, Grounding] = field(default_factory=dict)

    def __post_init__(self) -> None:
        for name in ("egress_micro_usd_per_gb", "storage_micro_usd_per_gb_month", "request_micro_usd_per_thousand",
                     "llm_input_micro_usd_per_1k_tokens", "llm_output_micro_usd_per_1k_tokens"):
            v = getattr(self, name)
            if isinstance(v, bool) or not isinstance(v, int) or v < 0:
                raise ValueError(f"{name} must be a non-negative int (micro-USD), got {v!r}")
        if self.compute_pricing not in COMPUTE_PRICING_RETAINED_BP:
            raise ValueError(
                f"compute_pricing must be one of {sorted(COMPUTE_PRICING_RETAINED_BP)}, got {self.compute_pricing!r}")

    @property
    def compute_retained_bp(self) -> int:
        """Basis points (per-10_000) of on-demand compute list price actually paid under this model."""
        return COMPUTE_PRICING_RETAINED_BP[self.compute_pricing]


@dataclass
class SystemModel:
    name: str
    components: dict[str, Component]
    flows: list[Flow]
    workload: Workload
    assumptions: list[Assumption] = field(default_factory=list)
    domain_flags: list[str] = field(default_factory=list)  # e.g. "high_stakes:elections"
    pricing: PricingRates = field(default_factory=PricingRates)  # usage rates (ADR-009 Tier 1)

    def scaled(self, system_rps: float) -> "SystemModel":
        """Return a copy with a different offered load (for what-if runs)."""
        return SystemModel(
            name=self.name,
            components=self.components,
            flows=self.flows,
            workload=Workload(system_rps=system_rps, description=f"what-if @ {system_rps:.0f} rps"),
            assumptions=self.assumptions,
            domain_flags=self.domain_flags,
            pricing=self.pricing,
        )
